# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockwidget_layer = QtWidgets.QDockWidget(MainWindow)
        self.dockwidget_layer.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockwidget_layer.setObjectName("dockwidget_layer")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treewidget_layer = QtWidgets.QTreeWidget(self.dockWidgetContents_4)
        self.treewidget_layer.setDragEnabled(False)
        self.treewidget_layer.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.treewidget_layer.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.treewidget_layer.setAutoExpandDelay(3)
        self.treewidget_layer.setColumnCount(2)
        self.treewidget_layer.setObjectName("treewidget_layer")
        self.treewidget_layer.headerItem().setText(0, "[]")
        self.treewidget_layer.headerItem().setText(1, "name")
        self.treewidget_layer.header().setCascadingSectionResizes(True)
        self.treewidget_layer.header().setDefaultSectionSize(32)
        self.treewidget_layer.header().setHighlightSections(False)
        self.verticalLayout.addWidget(self.treewidget_layer)
        self.dockwidget_layer.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockwidget_layer)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.toolBar_3 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_3.setObjectName("toolBar_3")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_3)
        self.action_FileOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/res/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_FileOpen.setIcon(icon)
        self.action_FileOpen.setObjectName("action_FileOpen")
        self.action_FileQuit = QtWidgets.QAction(MainWindow)
        self.action_FileQuit.setObjectName("action_FileQuit")
        self.action_FileSave = QtWidgets.QAction(MainWindow)
        self.action_FileSave.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/res/res/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_FileSave.setIcon(icon1)
        self.action_FileSave.setObjectName("action_FileSave")
        self.action_ViewWatershed = QtWidgets.QAction(MainWindow)
        self.action_ViewWatershed.setCheckable(True)
        self.action_ViewWatershed.setObjectName("action_ViewWatershed")
        self.action_ViewAutoUpdate = QtWidgets.QAction(MainWindow)
        self.action_ViewAutoUpdate.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/res/res/arrow_refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ViewAutoUpdate.setIcon(icon2)
        self.action_ViewAutoUpdate.setObjectName("action_ViewAutoUpdate")
        self.action_EditColor = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/res/res/color_wheel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_EditColor.setIcon(icon3)
        self.action_EditColor.setObjectName("action_EditColor")
        self.action_FileExportPicture = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/res/res/picture_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_FileExportPicture.setIcon(icon4)
        self.action_FileExportPicture.setObjectName("action_FileExportPicture")
        self.action_FileSaveAs = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/res/res/disk_multiple.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_FileSaveAs.setIcon(icon5)
        self.action_FileSaveAs.setObjectName("action_FileSaveAs")
        self.action_FileImportPicture = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/res/res/folder_picture.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_FileImportPicture.setIcon(icon6)
        self.action_FileImportPicture.setObjectName("action_FileImportPicture")
        self.action_ViewOriginal = QtWidgets.QAction(MainWindow)
        self.action_ViewOriginal.setCheckable(True)
        self.action_ViewOriginal.setObjectName("action_ViewOriginal")
        self.action_ViewOverlay = QtWidgets.QAction(MainWindow)
        self.action_ViewOverlay.setCheckable(True)
        self.action_ViewOverlay.setChecked(True)
        self.action_ViewOverlay.setObjectName("action_ViewOverlay")
        self.toolBar.addAction(self.action_FileOpen)
        self.toolBar.addAction(self.action_FileSave)
        self.toolBar.addAction(self.action_FileSaveAs)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_FileImportPicture)
        self.toolBar.addAction(self.action_FileExportPicture)
        self.toolBar_2.addAction(self.action_EditColor)
        self.toolBar_2.addSeparator()
        self.toolBar_2.addAction(self.action_ViewAutoUpdate)
        self.toolBar_3.addAction(self.action_ViewOriginal)
        self.toolBar_3.addAction(self.action_ViewOverlay)
        self.toolBar_3.addAction(self.action_ViewWatershed)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "watershed_region"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.toolBar_3.setWindowTitle(_translate("MainWindow", "toolBar_3"))
        self.action_FileOpen.setText(_translate("MainWindow", "Open..."))
        self.action_FileOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_FileQuit.setText(_translate("MainWindow", "Quit"))
        self.action_FileSave.setText(_translate("MainWindow", "Save"))
        self.action_FileSave.setToolTip(_translate("MainWindow", "Save"))
        self.action_FileSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_ViewWatershed.setText(_translate("MainWindow", "Watershed"))
        self.action_ViewWatershed.setToolTip(_translate("MainWindow", "Watershed"))
        self.action_ViewAutoUpdate.setText(_translate("MainWindow", "ViewAutoUpdate"))
        self.action_EditColor.setText(_translate("MainWindow", "Color"))
        self.action_FileExportPicture.setText(_translate("MainWindow", "Export Picture..."))
        self.action_FileSaveAs.setText(_translate("MainWindow", "SaveAs..."))
        self.action_FileImportPicture.setText(_translate("MainWindow", "Import Picture..."))
        self.action_ViewOriginal.setText(_translate("MainWindow", "Original"))
        self.action_ViewOriginal.setToolTip(_translate("MainWindow", "Original"))
        self.action_ViewOverlay.setText(_translate("MainWindow", "Overlay"))
        self.action_ViewOverlay.setToolTip(_translate("MainWindow", "Overlay"))

import resource_rc
